# Goal
std_msgs/Header header
string object_database
string training_features
string training_kdtree
string camera_frame
string root_frame
bool cull_snapshot
geometry_msgs/Point cull_from
geometry_msgs/Point cull_to
bool request_snapshot
---
# Result
bool success
sensor_msgs/PointCloud2 snapshot_cloud
sensor_msgs/PointCloud2 best_cluster
float64 match_score
geometry_msgs/PoseArray pregrasps
geometry_msgs/PoseArray grasps
---
# Feedback
float64 elapsed_time

