constraints:

    arm_1_shoulder_twist:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_2_shoulder_lift:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_3_elbow_twist:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_4_elbow_lift:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_5_wrist_twist:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_6_wrist_lift:
        trajectory_degs: 1.0
        goal_degs: 5.0

    arm_7_gripper_lift:
        trajectory_degs: 1.0
        goal_degs: 5.0

    end_effector:
        trajectory_m: 0.04
        goal_m: 0.04

    goal_time: 0.0

    stopped_velocity_tolerance: 0.01
