controller_list:
    - name: rcta_joint_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - limb_right_joint1
        - limb_right_joint2
        - limb_right_joint3
        - limb_right_joint4
        - limb_right_joint5
        - limb_right_joint6
        - limb_right_joint7
        - torso_joint1
    - name: rcta_right_robotiq_controller
      action_ns: gripper_action
      type: GripperCommand
      default: true
      joints: []

