# kinematics plugin modified here for convenience, but this SHOULD be tested
# against the arm planner to ensure the behavior doesn't regress in any way.
# This plugin is primarily required to be used with the object manipulation
# planner, but could also benefit the arm planner.
left_arm:
  kinematics_solver: custom_kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
right_arm:
  kinematics_solver: custom_kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
left_arm_and_torso:
  kinematics_solver: custom_kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
right_arm_and_torso:
  kinematics_solver: custom_kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
