one_degree: &one_degree 0.017453292519943

right_arm:
  planner_configs:
    right_arm_ARA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_LARA_BFS_ML:
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
left_arm:
  planner_configs:
    ARA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: LeftArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: LeftArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault

right_arm_and_torso:
  planner_configs:
    right_arm_and_torso_ARA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_MHA_BFS_ML:
      search_config: MHAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_LARA_BFS_ML:
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault

right_arm_torso_base:
  planner_configs:
    ARA_BFS_WS:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmTorsoBaseWorkspace
      shortcut_config: PVJointConfigDefault
    EGWA_BFSEG_WSEG:
      search_config: EGWAConfigDefault
      heuristic_config: BFSEGraphConfig
      graph_config: RightArmTorsoBaseWorkspaceEGraph
      shortcut_config: PVJointConfigDefault
    OBJECT_MANIP:
      search_config: EGWAConfigDefault
      heuristic_config: ObjectManipHeuristic
      graph_config: RightArmTorsoBaseWorkspaceEGraph
      shortcut_config: NoShortcutting

both_arms_and_torso:
  planner_configs:
    ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: BothArmsAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault

search_configs:
  ARAConfigDefault:
    search: arastar
    epsilon: 100.0
    improve_solution: false
    bound_expansions: true
  MHAConfigDefault:
    search: mhastar
    epsilon: 100.0
    mha_epsilon: 100.0
  LARAConfigDefault:
    search: larastar
    epsilon: 100.0
  EGWAConfigDefault:
    search: egwastar
    epsilon: 100.0

heuristic_configs:
  BFSConfigDefault:
    heuristic: bfs
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    bfs_sphere_radius: 0.02
  BFSEGraphConfig:
    heuristic: bfs_egraph
    egraph_epsilon: 50.0
    bfs_res_x: 0.04
    bfs_res_y: 0.04
    bfs_res_z: 0.04
    bfs_sphere_radius: 0.02
  JointDistConfigDefault:
    heuristic: joint_distance
  ObjectManipHeuristic:
    heuristic: object_manip

    # when the base distance is above this threshold, the base theta
    # term in the heuristic includes turning toward the nearest e-graph
    # state, and then turning to the orientation of the e-graph state;
    # otherwise, the base theta term only includes turning toward the
    # nearest e-graph state
    heading_thresh: 0.05 # cabinet1, cabinet2@35
    #heading_thresh: 0.1
    #heading_thresh: 0.15 # cabinet_demo@60

    # tolerance before the base theta term is dropped to 0
    theta_db: 0.0349066

    # tolerance before the base position term is dropped to 0
    pos_db: 0.1 # cabinet1, cabinet2@35
    #pos_db: 0.2 # cabinet_demo@60

graph_configs:
  RightArmManipLatticeConfigDefault:
    graph: manip
    discretization:
      limb_right_joint1: *one_degree
      limb_right_joint2: *one_degree
      limb_right_joint3: *one_degree
      limb_right_joint4: *one_degree
      limb_right_joint5: *one_degree
      limb_right_joint6: *one_degree
      limb_right_joint7: *one_degree
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmManipLatticeEgraphConfigDefault:
    graph: manip_lattice_egraph
    discretization:
      limb_right_joint1: *one_degree
      limb_right_joint2: *one_degree
      limb_right_joint3: *one_degree
      limb_right_joint4: *one_degree
      limb_right_joint5: *one_degree
      limb_right_joint6: *one_degree
      limb_right_joint7: *one_degree
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmWorkspaceConfigDefault:
    graph: workspace
  RightArmTorsoBaseWorkspace:
    graph: workspace
    discretization:
        fk_pos_x: 0.05
        fk_pos_y: 0.05
        fk_pos_z: 0.05
        fk_rot_r: 0.0872664             # 5 degrees = 72 angles
        fk_rot_p: 0.0872664             # 5 degrees = 72 angles
        fk_rot_y: 0.0872664             # 5 degrees = 72 angles
        limb_right_joint3: 0.0872664
        torso_joint1: 0.0872664
        world_joint_x: 0.05
        world_joint_y: 0.05
        world_joint_theta: 0.392699
  RightArmTorsoBaseWorkspaceEGraph:
    graph: workspace_egraph
    discretization:
        fk_pos_x: 0.05
        fk_pos_y: 0.05
        fk_pos_z: 0.05
        fk_rot_r: *one_degree
#        fk_rot_p: 0.0698132             # 4 degree = 46 angles #181 angles
        fk_rot_p: *one_degree
        fk_rot_y: 0.0872664             # 5 degrees = 72 angles
        limb_right_joint3: 0.0872664    # 5 degrees
        torso_joint1: 0.0872664         # 5 degrees
        world_joint_x: 0.05
        world_joint_y: 0.05
        world_joint_theta: 0.392699     # 22.5 degrees = 16 angles
        hinge: 0.00001
  LeftArmManipLatticeConfigDefault:
    graph: manip
    discretization:
      limb_left_joint1: *one_degree
      limb_left_joint2: *one_degree
      limb_left_joint3: *one_degree
      limb_left_joint4: *one_degree
      limb_left_joint5: *one_degree
      limb_left_joint6: *one_degree
      limb_left_joint7: *one_degree
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  BothArmsAndTorsoManipLatticeConfigDefault:
    graph: manip
    discretization:
      torso_joint1: *one_degree
      limb_left_joint1: *one_degree
      limb_left_joint2: *one_degree
      limb_left_joint3: *one_degree
      limb_left_joint4: *one_degree
      limb_left_joint5: *one_degree
      limb_left_joint6: *one_degree
      limb_left_joint7: *one_degree
      limb_right_joint1: *one_degree
      limb_right_joint2: *one_degree
      limb_right_joint3: *one_degree
      limb_right_joint4: *one_degree
      limb_right_joint5: *one_degree
      limb_right_joint6: *one_degree
      limb_right_joint7: *one_degree
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmAndTorsoManipLatticeConfigDefault:
    graph: manip
    # angular resolution of each active joint variable
    discretization:
      limb_right_joint1: *one_degree
      limb_right_joint2: *one_degree
      limb_right_joint3: *one_degree
      limb_right_joint4: *one_degree
      limb_right_joint5: *one_degree
      limb_right_joint6: *one_degree
      limb_right_joint7: *one_degree
      torso_joint1: *one_degree
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4

shortcut_configs:
  PVJointConfigDefault:
    shortcut_path: true
    shortcutter: joint_position_velocity_space
    interpolate_path: true
  NoShortcutting:
    shortcut_path: false
    interpolate_path: false
