#!/usr/bin/env python

import sys
import subprocess

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print 'Usage: {0} <path_to_urdf> <output_filename>'.format(sys.argv[0])
        exit(1)

    ret = subprocess.call(['rospack', 'find', 'collada_urdf'])
    if ret:
        print 'The collada_urdf package is required to convert URDF to COLLADA'
        exit(2)

    ret = subprocess.call(['rosrun', 'collada_urdf', 'urdf_to_collada', sys.argv[1], sys.argv[2]])

    if ret:
        print 'Failed to write COLLADA file'
        exit(3)

    exit(0)

