clients:
  - name: rcta_joint_trajectory_controller/follow_joint_trajectory
    joints:
      - torso_joint1
      - limb_right_joint1
      - limb_right_joint2
      - limb_right_joint3
      - limb_right_joint4
      - limb_right_joint5
      - limb_right_joint6
      - limb_right_joint7
      - limb_left_joint1
      - limb_left_joint2
      - limb_left_joint3
      - limb_left_joint4
      - limb_left_joint5
      - limb_left_joint6
      - limb_left_joint7
